// Generated by ReScript, PLEASE EDIT WITH CARE


function add(a, b) {
  return a + b;
}

function inc(param) {
  return 1 + param;
}

var a = 1 + 6;

function named_add(num1, num2) {
  return num1 + num2;
}

var b = 7 + 6;

var lyovson = {
  name: "Lyovson",
  age: 31
};

export {
  add ,
  inc ,
  a ,
  named_add ,
  b ,
  lyovson ,
}
/* No side effect */
